### ISSUE TITLE
Slow transfers WAI?

### ISSUE THREAD

**Issue by pooslice** [cathery/sys-ftpd-light#10]
So this might not be an issue, but I don't know where else to write this so I'll put it here.

Transfer speeds seem to be limited to about 950 KiB/s for single files. This is an improvement from earlier releases where I maxed out at about 450.
I know this is a sys module and this might be limited to this by design. but ftpd by mtheall is about 3-4x faster hitting about 4MB for single files, and up to 6-7MB/s for multiple transfers.

This makes this limiting to just small files, or updating configs and such so it still has it's purpose.

**Comment by cathery** [comment]
The transfer speed is mostly decided by the amount of memory i allocate to the FTP buffers. Since this is a sysmodule, low memory usage is first priority. I actually wanted to make it even lower, but it got generally frowned upon, so i kept it the same as sys-ftpd. So yeah, this is supposed to be a lightweight sysmodule (as signified by the name) and transfer speeds won't be too high. Anytime you want to do full speed transfers, you can just open mtheall's ftpd app and do your thing.
